# Generated by Django 3.1 on 2020-08-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_auto_20200811_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['inventory_group', 'grade', 'size_left']},
        ),
        migrations.AddField(
            model_name='product',
            name='size_left',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
