# Generated by Django 3.1 on 2020-08-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_auto_20200811_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['inventory_group', 'grade', 'size_left', 'size_right', 'length_value']},
        ),
        migrations.AddField(
            model_name='product',
            name='length_value',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='size_right',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
