# Generated by Django 3.1 on 2020-08-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0004_auto_20200811_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_model',
            name='order_quantity1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #1'),
        ),
        migrations.AlterField(
            model_name='purchase_order_model',
            name='unique_product1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #1'),
        ),
    ]
