# Generated by Django 3.1 on 2020-08-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0005_auto_20200815_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_order_model',
            name='order_quantity1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #1'),
        ),
        migrations.AlterField(
            model_name='sales_order_model',
            name='so_order_quantity1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #1'),
        ),
        migrations.AlterField(
            model_name='sales_order_model',
            name='so_unique_product1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #1'),
        ),
        migrations.AlterField(
            model_name='sales_order_model',
            name='unique_product1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #1'),
        ),
    ]
