# Generated by Django 3.1 on 2020-08-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0007_auto_20200815_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #10'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity11',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #11'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity12',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #12'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity13',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #13'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity14',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #14'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity15',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #15'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity16',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #16'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity17',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #17'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity18',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #18'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity19',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #19'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity20',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #20'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #3'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #4'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #5'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #6'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity7',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #7'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity8',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #8'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='order_quantity9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulfillment Quantity #9'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #10'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity11',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #11'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity12',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #12'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity13',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #13'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity14',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #14'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity15',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #15'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity16',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #16'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity17',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #17'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity18',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #18'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity19',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #19'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity20',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #20'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #3'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #4'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #5'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #6'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity7',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #7'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity8',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #8'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_order_quantity9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Quantity #9'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product10',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #10'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product11',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #11'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product12',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #12'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product13',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #13'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product14',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #14'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product15',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #15'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product16',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #16'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product17',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #17'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product18',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #18'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product19',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #19'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product20',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #20'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #3'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #4'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #5'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product6',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #6'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product7',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #7'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product8',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #8'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='so_unique_product9',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unique Product #9'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product10',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #10'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product11',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #11'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product12',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #12'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product13',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #13'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product14',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #14'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product15',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #15'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product16',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #16'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product17',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #17'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product18',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #18'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product19',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #19'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product20',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #20'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #3'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #4'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #5'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product6',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #6'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product7',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #7'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product8',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #8'),
        ),
        migrations.AddField(
            model_name='sales_order_model',
            name='unique_product9',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fulfillment Product #9'),
        ),
    ]
