# Generated by Django 3.1 on 2020-08-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0008_auto_20200815_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_order_model',
            name='ship_by',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ship By'),
        ),
    ]
